//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_DVDs.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appDVDsEntities : DbContext
    {

        public static appDVDsEntities _context;

        public static appDVDsEntities GetContext()
        {
            if (_context == null)
                _context = new appDVDsEntities();
            return _context;
        }
        public appDVDsEntities()
            : base("name=appDVDsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DVDsDB> DVDsDBs { get; set; }
        public virtual DbSet<sellersDB> sellersDBs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<teamDB> teamDBs { get; set; }
    }
}
