//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_DVDs.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellersDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sellersDB()
        {
            this.DVDsDBs = new HashSet<DVDsDB>();
        }
    
        public int C_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string company { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string site { get; set; }
        public string note { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVDsDB> DVDsDBs { get; set; }
    }
}
