//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_DVDs.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class teamDB
    {
        public int C_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string post { get; set; }
        public Nullable<int> age { get; set; }
        public string department { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> role { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
    }
}
